static const char black[]         = "#${base00}";
static const char blue[]          = "#${base0D}"; // focused window border
static const char gray2[]         = "#${base00}"; // unfocused window border
static const char gray3[]         = "#${base01}";
static const char gray4[]         = "#${base00}";
static const char green[]         = "#${base0C}";
static const char orange[]        = "#${base09}";
static const char pink[]          = "#${base0E}";
static const char red[]           = "#${base08}";
static const char white[]         = "#${base06}";
static const char yellow[]        = "#${base0B}";
static const char col_borderbar[] = "#${base00}";
