static const char black[]         = "#0A0E14";
static const char blue[]          = "#39BAE6"; // focused window border
static const char gray2[]         = "#3D424D"; // unfocused window border
static const char gray3[]         = "#B3B1AD";
static const char gray4[]         = "#626A73";
static const char green[]         = "#C2D94C";
static const char orange[]        = "#FF8F40";
static const char pink[]          = "#F07178";
static const char red[]           = "#FF3333";
static const char white[]         = "#FDFDFD"; // <- made up
static const char yellow[]        = "#E6B450";
static const char col_borderbar[] = "#0A0E14";
