static const char black[]         = "";
static const char blue[]          = ""; // focused window border
static const char gray2[]         = ""; // unfocused window border
static const char gray3[]         = "";
static const char gray4[]         = "";
static const char green[]         = "";
static const char orange[]        = "";
static const char pink[]          = "";
static const char red[]           = "";
static const char white[]         = "";
static const char yellow[]        = "";
static const char col_borderbar[] = "";
